<?php

define('VIDEO_NEEDS_APPROVAL',		  	0);
define('VIDEO_STATUS_TRANSLATING',  	1);
define('VIDEO_STATUS_SYNCHRONIZING',  	2);
define('VIDEO_STATUS_PROOFREADING',  	3);
define('VIDEO_STATUS_FINISHED',  		4);

define('USER_NOT_AUTHORIZED',  	0);
define('USER_AUTH_OPERATOR',  	1);
define('USER_AUTH_ADMIN',  		2);
define('USER_AUTH_SUPERADMIN',  3);