<?php

define('VIDEO_FOR_APPROVAL',		  	0);
define('VIDEO_STATUS_TRANSLATING',  	1);
define('VIDEO_STATUS_SYNCHRONIZING',  	2);
define('VIDEO_STATUS_PROOFREADING',  	3);
define('VIDEO_STATUS_FINISHED',  		4);
define('VIDEO_STATUS_REJECTED',  		5);

define('USER_NOT_AUTHORIZED',  	0);
define('USER_AUTH_OPERATOR',  	1);
define('USER_AUTH_ADMIN',  		2);
define('USER_AUTH_SUPERADMIN',  3);

define('TASK_SUGGESTED_VIDEO', 	1);
define('TASK_APPROVED_VIDEO', 	2);
define('TASK_REJECTED_VIDEO', 	3);

define('TASK_IS_TRANSLATING', 	4);
define('TASK_IS_SYNCHRONIZING', 5);
define('TASK_IS_PROOFREADING', 	6);

define('TASK_ADVANCE_TO_SYNC', 	7);
define('TASK_ADVANCE_TO_PROOF', 8);
define('TASK_FINISH_VIDEO', 	9);

define('TASK_BACK_TO_TRANS', 	10);
define('TASK_BACK_TO_SYNC', 	11);
define('TASK_BACK_TO_PROOF', 	12);